In [1]:
import pandas as pd

In [12]:
pd.read_csv(r'E:\Hackathons\AmEx-Campus-Challenge-2026\6a3eb196bc7a3_campus_challenge_r1_data.csv', index_col = 'id') # alwyas use r in front of paths in python

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23
id,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0,1,98615.44,5620.938246,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0,49.280210,1960.0,1900.0,2.0,1.0,0.00,2.0,NaN
1,0.000000,0,0,21241.06,10196.878460,13865.4026,425.04840,27.9986,0.0000,494.8428,...,196.0000,5.0,63.759364,34300.0,34650.0,3.0,2.0,163620.00,3.0,NaN
2,1224.690475,0,1,NaN,16.160000,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0,19.646836,NaN,NaN,1.0,1.0,NaN,9.0,NaN
3,0.000000,1,0,NaN,1635.316863,3231.1968,-269.15308,0.0000,0.0000,48.5520,...,0.0000,0.0,9.143074,12348.0,12474.0,2.0,1.0,NaN,5.0,NaN
4,3824.366700,0,0,7140.87,5007.271790,4064.2152,16079.35060,377.9055,556.9740,5354.3280,...,0.0000,11.0,63.759364,3672.0,3528.0,3.0,1.0,68640.00,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,0.000000,0,0,140995.62,0.000000,26017.2042,84888.10260,2318.6227,5343.4252,12996.2722,...,12.7500,4.0,61.827262,NaN,NaN,1.0,1.0,0.00,NaN,NaN
499996,14524.638800,0,0,16548.20,387.496932,7941.0602,52191.75780,483.7698,7404.7410,21650.5820,...,0.0000,0.0,64.403398,NaN,NaN,2.0,2.0,65067.84,6.0,NaN
499997,0.000000,0,0,79328.70,6654.585300,0.0000,1529.98580,0.0000,0.0000,0.0000,...,0.0000,1.0,64.403398,NaN,NaN,1.0,1.0,14212.97,15.0,NaN
499998,17967.726330,0,0,2.10,4393.267105,0.0000,322.22100,0.0000,0.0000,3.1680,...,0.0000,0.0,61.183228,NaN,NaN,1.0,1.0,0.00,4.0,NaN
499999,12518.042340,0,0,NaN,342.760334,3478.0057,2497.70460,373.0548,201.3363,1697.7696,...,38.5517,0.0,64.403398,26631.0,26362.0,3.0,1.0,NaN,13.0,NaN

In [22]:
pd.read_csv(r'E:\Hackathons\AmEx-Campus-Challenge-2026\6a3eb196bc7a3_campus_challenge_r1_data.csv', index_col = 'id', nrows = 10)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23
id,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0,1,98615.44,5620.938246,NaN,NaN,NaN,NaN,NaN,...,0.0000,0,49.280210,1960.0,1900.0,2,1,0.00,2.0,NaN
1,0.000000,0,0,21241.06,10196.878460,13865.4026,425.04840,27.9986,0.0000,494.84280,...,196.0000,5,63.759364,34300.0,34650.0,3,2,163620.00,3.0,NaN
2,1224.690475,0,1,NaN,16.160000,NaN,NaN,NaN,NaN,NaN,...,0.0000,0,19.646836,NaN,NaN,1,1,NaN,9.0,NaN
3,0.000000,1,0,NaN,1635.316863,3231.1968,-269.15308,0.0000,0.0000,48.55200,...,0.0000,0,9.143074,12348.0,12474.0,2,1,NaN,5.0,NaN
4,3824.366700,0,0,7140.87,5007.271790,4064.2152,16079.35060,377.9055,556.9740,5354.32800,...,0.0000,11,63.759364,3672.0,3528.0,3,1,68640.00,0.0,NaN
5,13693.126850,0,0,NaN,1092.540977,18506.0007,10912.45980,553.7792,1855.9629,2281.36260,...,200.0000,11,63.759364,NaN,NaN,1,1,NaN,2.0,1.0
6,0.000000,0,0,52834.93,8649.815878,16386.3264,-274.64600,0.0000,5906.3202,2815.34470,...,0.0000,1,64.403398,40501.0,40501.0,3,1,182057.55,0.0,NaN
7,10878.184620,0,0,NaN,2110.565533,33868.1336,40748.36140,3026.5389,7806.9777,21217.57036,...,107.1408,9,64.403398,30600.0,30300.0,2,1,NaN,7.0,1.0
8,2901.104008,0,1,NaN,47.515737,NaN,NaN,NaN,NaN,NaN,...,21.7800,6,41.854991,NaN,NaN,1,1,NaN,4.0,NaN
9,1794.831500,0,0,NaN,11005.853170,638.0192,4802.10560,626.5350,0.0000,2069.20820,...,200.0000,9,64.403398,NaN,NaN,1,1,NaN,NaN,NaN

In [23]:
cols = ["id",
    "Average Revolve Balance in last 12m",
    "Cancellation Calls in last 12m",
    "Cancellation Calls due to Collection",
    "Rewards Points Balance",
    "Total Spend in last 12m",
    "Airlines Spend in 12m",
    "Other Spend in 12m",
    "Entertainment Spend in 12m",
    "Lodging Spend in 12m",
    "Dining Spend in 12m",
    "Average Risk Score in 12m",
    "Login Counts to website",
    "Lounge Access Count",
    "Credits used in airlines",
    "Cab benefits usage",
    "Entertainment Credit Used Amount",
    "Total Lend Line Amount",
    "Total Consumer Lend Line Amount",
    "Number of Supplementary Accounts",
    "Count of Active Charge Cards",
    "Rewards point redeemed in 12months",
    "Emails Open in Last 6 months",
    "Emails Clicked in Last 6 months"
]

In [27]:
df = pd.read_csv(
    r"E:\Hackathons\AmEx-Campus-Challenge-2026\6a3eb196bc7a3_campus_challenge_r1_data.csv",
    names=cols,
    header=0,
    index_col='id'
)
df

,Average Revolve Balance in last 12m,Cancellation Calls in last 12m,Cancellation Calls due to Collection,Rewards Points Balance,Total Spend in last 12m,Airlines Spend in 12m,Other Spend in 12m,Entertainment Spend in 12m,Lodging Spend in 12m,Dining Spend in 12m,...,Credits used in airlines,Cab benefits usage,Entertainment Credit Used Amount,Total Lend Line Amount,Total Consumer Lend Line Amount,Number of Supplementary Accounts,Count of Active Charge Cards,Rewards point redeemed in 12months,Emails Open in Last 6 months,Emails Clicked in Last 6 months
id,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0,1,98615.44,5620.938246,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0,49.280210,1960.0,1900.0,2.0,1.0,0.00,2.0,NaN
1,0.000000,0,0,21241.06,10196.878460,13865.4026,425.04840,27.9986,0.0000,494.8428,...,196.0000,5.0,63.759364,34300.0,34650.0,3.0,2.0,163620.00,3.0,NaN
2,1224.690475,0,1,NaN,16.160000,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0,19.646836,NaN,NaN,1.0,1.0,NaN,9.0,NaN
3,0.000000,1,0,NaN,1635.316863,3231.1968,-269.15308,0.0000,0.0000,48.5520,...,0.0000,0.0,9.143074,12348.0,12474.0,2.0,1.0,NaN,5.0,NaN
4,3824.366700,0,0,7140.87,5007.271790,4064.2152,16079.35060,377.9055,556.9740,5354.3280,...,0.0000,11.0,63.759364,3672.0,3528.0,3.0,1.0,68640.00,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,0.000000,0,0,140995.62,0.000000,26017.2042,84888.10260,2318.6227,5343.4252,12996.2722,...,12.7500,4.0,61.827262,NaN,NaN,1.0,1.0,0.00,NaN,NaN
499996,14524.638800,0,0,16548.20,387.496932,7941.0602,52191.75780,483.7698,7404.7410,21650.5820,...,0.0000,0.0,64.403398,NaN,NaN,2.0,2.0,65067.84,6.0,NaN
499997,0.000000,0,0,79328.70,6654.585300,0.0000,1529.98580,0.0000,0.0000,0.0000,...,0.0000,1.0,64.403398,NaN,NaN,1.0,1.0,14212.97,15.0,NaN
499998,17967.726330,0,0,2.10,4393.267105,0.0000,322.22100,0.0000,0.0000,3.1680,...,0.0000,0.0,61.183228,NaN,NaN,1.0,1.0,0.00,4.0,NaN
499999,12518.042340,0,0,NaN,342.760334,3478.0057,2497.70460,373.0548,201.3363,1697.7696,...,38.5517,0.0,64.403398,26631.0,26362.0,3.0,1.0,NaN,13.0,NaN

# Understanding your Data

In [ ]:
df.shape # shape of the data

(500000, 23)

In [31]:
df.sample(10) # gives us 10 random samples of data

,Average Revolve Balance in last 12m,Cancellation Calls in last 12m,Cancellation Calls due to Collection,Rewards Points Balance,Total Spend in last 12m,Airlines Spend in 12m,Other Spend in 12m,Entertainment Spend in 12m,Lodging Spend in 12m,Dining Spend in 12m,...,Credits used in airlines,Cab benefits usage,Entertainment Credit Used Amount,Total Lend Line Amount,Total Consumer Lend Line Amount,Number of Supplementary Accounts,Count of Active Charge Cards,Rewards point redeemed in 12months,Emails Open in Last 6 months,Emails Clicked in Last 6 months
id,,,,,,,,,,,,,,,,,,,,,
104188,72.668200,0,0,1687.08,3782.768343,6507.6017,12400.5684,707.6832,0.0000,1269.2085,...,196.4952,4.0,64.403398,25272.0,25029.0,2.0,1.0,1088.78,0.0,NaN
170905,17428.694540,0,0,697899.35,13596.279900,0.0000,1992.4188,0.0000,0.0000,0.0000,...,0.0000,0.0,63.115330,37521.0,38658.0,3.0,1.0,178290.32,0.0,NaN
257953,0.000000,0,0,21644.37,8769.627426,6139.9614,58870.2409,4036.8069,991.2994,3565.6643,...,200.0000,7.0,62.471296,NaN,NaN,1.0,1.0,86782.50,NaN,NaN
323486,1943.711334,1,0,NaN,0.420833,16451.9558,14351.3711,949.2068,5979.0780,5695.0068,...,200.0000,10.0,64.403398,NaN,NaN,1.0,1.0,NaN,NaN,NaN
193045,0.000000,1,0,37426.48,2163.225805,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0,9.054307,NaN,NaN,1.0,1.0,31946.40,NaN,NaN
393528,17967.726330,0,0,NaN,2839.129204,8598.4220,49989.3024,1640.1924,1353.3898,11972.6048,...,196.0000,4.0,63.115330,27068.0,27068.0,3.0,2.0,NaN,15.0,1.0
469192,2579.702184,0,1,NaN,2002.895759,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0,51.231901,4444.0,4312.0,4.0,2.0,NaN,NaN,NaN
423830,0.000000,1,0,2036.03,2065.531471,0.0000,8575.0522,0.0000,0.0000,1208.2512,...,0.0000,0.0,9.320610,25500.0,26250.0,2.0,1.0,12817.58,2.0,NaN
156481,0.000000,0,0,23067.84,2959.690990,0.0000,490.1787,0.0000,0.0000,0.0000,...,0.0000,0.0,61.827262,NaN,NaN,1.0,1.0,0.00,NaN,NaN
137877,0.000000,0,0,NaN,1687.638205,6653.9598,61955.4099,0.0000,527.8084,229.3434,...,0.0000,6.0,64.403398,10560.0,10450.0,3.0,1.0,NaN,0.0,NaN

In [32]:
df.info() # gives us information regarding null values, count, non-null values

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 23 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Average Revolve Balance in last 12m   500000 non-null  float64
 1   Cancellation Calls in last 12m        500000 non-null  int64
 2   Cancellation Calls due to Collection  500000 non-null  int64
 3   Rewards Points Balance                242772 non-null  float64
 4   Total Spend in last 12m               493660 non-null  float64
 5   Airlines Spend in 12m                 384302 non-null  float64
 6   Other Spend in 12m                    384302 non-null  float64
 7   Entertainment Spend in 12m            384302 non-null  float64
 8   Lodging Spend in 12m                  384302 non-null  float64
 9   Dining Spend in 12m                   384302 non-null  float64
 10  Average Risk Score in 12m             497490 non-null  float64
 11  Login Counts to website               474995 non-null  float64
 12  Lounge Access Count                   486284 non-null  float64
 13  Credits used in airlines              486284 non-null  float64
 14  Cab benefits usage                    486284 non-null  float64
 15  Entertainment Credit Used Amount      486284 non-null  float64
 16  Total Lend Line Amount                207746 non-null  float64
 17  Total Consumer Lend Line Amount       190556 non-null  float64
 18  Number of Supplementary Accounts      499978 non-null  float64
 19  Count of Active Charge Cards          499899 non-null  float64
 20  Rewards point redeemed in 12months    242772 non-null  float64
 21  Emails Open in Last 6 months          405346 non-null  float64
 22  Emails Clicked in Last 6 months       61035 non-null   float64
dtypes: float64(21), int64(2)
memory usage: 87.7 MB

In [33]:
df.isnull().sum() # gives us total amount of missing values in each column in pandas series format

Average Revolve Balance in last 12m          0
Cancellation Calls in last 12m               0
Cancellation Calls due to Collection         0
Rewards Points Balance                  257228
Total Spend in last 12m                   6340
Airlines Spend in 12m                   115698
Other Spend in 12m                      115698
Entertainment Spend in 12m              115698
Lodging Spend in 12m                    115698
Dining Spend in 12m                     115698
Average Risk Score in 12m                 2510
Login Counts to website                  25005
Lounge Access Count                      13716
Credits used in airlines                 13716
Cab benefits usage                       13716
Entertainment Credit Used Amount         13716
Total Lend Line Amount                  292254
Total Consumer Lend Line Amount         309444
Number of Supplementary Accounts            22
Count of Active Charge Cards               101
Rewards point redeemed in 12months      257228
Emails Open in Last 6 months             94654
Emails Clicked in Last 6 months         438965
dtype: int64

In [34]:
df.describe() # gives us some of the mathematical values of each column

,Average Revolve Balance in last 12m,Cancellation Calls in last 12m,Cancellation Calls due to Collection,Rewards Points Balance,Total Spend in last 12m,Airlines Spend in 12m,Other Spend in 12m,Entertainment Spend in 12m,Lodging Spend in 12m,Dining Spend in 12m,...,Credits used in airlines,Cab benefits usage,Entertainment Credit Used Amount,Total Lend Line Amount,Total Consumer Lend Line Amount,Number of Supplementary Accounts,Count of Active Charge Cards,Rewards point redeemed in 12months,Emails Open in Last 6 months,Emails Clicked in Last 6 months
count,500000.000000,500000.000000,500000.000000,242772.000000,493660.000000,384302.000000,384302.000000,384302.000000,384302.000000,384302.000000,...,486284.000000,486284.000000,486284.000000,207746.000000,190556.000000,499978.000000,499899.000000,242772.000000,405346.000000,61035.000000
mean,2467.312088,0.173948,0.108608,126607.131109,3464.813312,10032.050115,30821.546800,1522.992929,1651.736560,4536.375279,...,43.062608,3.992842,53.406679,24164.757131,21976.069885,1.800955,1.192771,62730.261250,4.575804,1.309904
std,4801.261745,0.379065,0.311147,183366.588497,3710.776424,13981.489112,39491.042972,2521.700018,2869.234123,6013.242074,...,71.945451,3.884681,17.841910,17461.891993,15343.872912,0.965363,0.394475,98682.348271,4.169967,0.599658
min,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,-274.646000,0.000000,0.000000,0.000000,...,0.000000,0.000000,8.876771,1000.000000,1000.000000,1.000000,1.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,8097.067500,668.571423,636.826300,3337.599825,0.000000,0.000000,325.187050,...,0.000000,0.000000,47.816441,9800.000000,9310.000000,1.000000,1.000000,0.000000,1.000000,1.000000
50%,0.000000,0.000000,0.000000,50705.190000,2165.850798,4022.766000,14396.270950,303.993300,264.746000,1801.797000,...,0.000000,3.000000,63.115330,21728.000000,19998.000000,2.000000,1.000000,11186.360000,3.000000,1.000000
75%,2436.194862,0.000000,0.000000,150490.920000,4911.806492,12870.158300,41278.605275,1777.084625,1809.549225,6311.077775,...,72.100000,7.000000,64.403398,34650.000000,33026.000000,2.000000,1.000000,84460.000000,7.000000,1.000000
max,17967.726330,1.000000,1.000000,697899.350000,13596.279900,52198.432000,146700.554000,9419.874000,10828.994000,21650.582000,...,200.000000,11.000000,64.403398,63800.000000,54800.000000,4.000000,2.000000,365166.150000,15.000000,3.000000

In [ ]:
#Duplicate Values in our data
df.duplicated().sum()

np.int64(97)

In [ ]:
# Correlation between cols
# very important to understand the relation between the input cols and output cols
df.corr()

,Average Revolve Balance in last 12m,Cancellation Calls in last 12m,Cancellation Calls due to Collection,Rewards Points Balance,Total Spend in last 12m,Airlines Spend in 12m,Other Spend in 12m,Entertainment Spend in 12m,Lodging Spend in 12m,Dining Spend in 12m,...,Credits used in airlines,Cab benefits usage,Entertainment Credit Used Amount,Total Lend Line Amount,Total Consumer Lend Line Amount,Number of Supplementary Accounts,Count of Active Charge Cards,Rewards point redeemed in 12months,Emails Open in Last 6 months,Emails Clicked in Last 6 months
Average Revolve Balance in last 12m,1.000000,-0.201072,0.173034,-0.049796,0.031887,0.037332,0.107974,0.083387,0.073349,0.094419,...,-0.064085,-0.034192,0.088158,-0.064539,-0.052396,0.011797,-0.017104,0.046782,0.071878,0.008297
Cancellation Calls in last 12m,-0.201072,1.000000,-0.158499,-0.088482,-0.015272,-0.179435,-0.202594,-0.161323,-0.162409,-0.209160,...,0.002213,-0.106353,-0.519401,0.058275,0.062251,0.030747,0.021373,-0.055740,-0.034583,-0.031842
Cancellation Calls due to Collection,0.173034,-0.158499,1.000000,-0.079038,-0.022840,-0.019588,-0.011147,-0.012746,-0.015974,-0.017250,...,-0.172031,-0.215484,-0.399639,-0.211130,-0.228810,0.051450,0.040469,-0.031298,0.090208,0.013358
Rewards Points Balance,-0.049796,-0.088482,-0.079038,1.000000,0.094874,0.290202,0.331585,0.223183,0.252808,0.249325,...,0.038023,-0.004881,0.116203,0.137775,0.104618,-0.033149,0.103101,0.152249,0.042737,0.088536
Total Spend in last 12m,0.031887,-0.015272,-0.022840,0.094874,1.000000,0.127123,0.075780,0.078349,0.118685,0.037839,...,0.031788,0.014749,0.032410,0.157969,0.144852,0.061311,-0.005838,0.084903,0.074443,0.030592
Airlines Spend in 12m,0.037332,-0.179435,-0.019588,0.290202,0.127123,1.000000,0.504733,0.506347,0.703491,0.543408,...,0.224896,0.151131,0.210952,0.105893,0.113959,-0.122382,-0.044572,0.286496,0.027649,0.062963
Other Spend in 12m,0.107974,-0.202594,-0.011147,0.331585,0.075780,0.504733,1.000000,0.573589,0.476254,0.664629,...,0.094079,0.077107,0.217572,0.106475,0.104825,-0.126966,-0.060675,0.346071,0.055904,0.095959
Entertainment Spend in 12m,0.083387,-0.161323,-0.012746,0.223183,0.078349,0.506347,0.573589,1.000000,0.502234,0.619932,...,0.141069,0.152870,0.179489,0.084592,0.091804,-0.112101,-0.057391,0.243807,0.034980,0.057971
Lodging Spend in 12m,0.073349,-0.162409,-0.015974,0.252808,0.118685,0.703491,0.476254,0.502234,1.000000,0.560164,...,0.138142,0.100619,0.175629,0.087289,0.101382,-0.120458,-0.061751,0.250397,0.018867,0.061353
Dining Spend in 12m,0.094419,-0.209160,-0.017250,0.249325,0.037839,0.543408,0.664629,0.619932,0.560164,1.000000,...,0.134765,0.193726,0.223090,0.072293,0.083155,-0.171016,-0.124828,0.270417,0.018319,0.056497
Average Risk Score in 12m,0.196084,-0.175141,0.582645,-0.120502,-0.050264,-0.134404,-0.131680,-0.102203,-0.100209,-0.108190,...,-0.175577,-0.188468,-0.237827,-0.300380,-0.322456,0.066820,0.042890,-0.047656,0.130631,-0.013094
Login Counts to website,-0.071236,0.087977,-0.044171,-0.017407,-0.064714,0.013620,0.001535,-0.004864,-0.031669,-0.014399,...,0.173380,0.170169,-0.030365,0.126131,0.082523,0.261629,0.212861,0.063356,0.143746,0.076524
Lounge Access Count,-0.033931,-0.077128,-0.138970,0.006404,0.046537,0.176623,0.053244,0.107867,0.111917,0.104145,...,0.238676,0.257966,0.212326,0.086838,0.097000,-0.010363,-0.012152,0.009899,0.001636,-0.020656
Credits used in airlines,-0.064085,0.002213,-0.172031,0.038023,0.031788,0.224896,0.094079,0.141069,0.138142,0.134765,...,1.000000,0.318673,0.175350,0.113087,0.113594,0.033203,0.011224,0.056989,0.027540,-0.012770
Cab benefits usage,-0.034192,-0.106353,-0.215484,-0.004881,0.014749,0.151131,0.077107,0.152870,0.100619,0.193726,...,0.318673,1.000000,0.354229,0.110275,0.124170,0.007248,-0.028937,0.023361,0.017928,-0.037809
Entertainment Credit Used Amount,0.088158,-0.519401,-0.399639,0.116203,0.032410,0.210952,0.217572,0.179489,0.175629,0.223090,...,0.175350,0.354229,1.000000,0.099189,0.114471,-0.072486,-0.047523,0.057876,-0.037748,0.005344
Total Lend Line Amount,-0.064539,0.058275,-0.211130,0.137775,0.157969,0.105893,0.106475,0.084592,0.087289,0.072293,...,0.113087,0.110275,0.099189,1.000000,0.900134,0.388533,0.047687,0.119083,0.143557,0.062919
Total Consumer Lend Line Amount,-0.052396,0.062251,-0.228810,0.104618,0.144852,0.113959,0.104825,0.091804,0.101382,0.083155,...,0.113594,0.124170,0.114471,0.900134,1.000000,0.251779,-0.028220,0.084869,0.081407,0.029749
Number of Supplementary Accounts,0.011797,0.030747,0.051450,-0.033149,0.061311,-0.122382,-0.126966,-0.112101,-0.120458,-0.171016,...,0.033203,0.007248,-0.072486,0.388533,0.251779,1.000000,0.544209,0.013540,0.367762,0.096413
Count of Active Charge Cards,-0.017104,0.021373,0.040469,0.103101,-0.005838,-0.044572,-0.060675,-0.057391,-0.061751,-0.124828,...,0.011224,-0.028937,-0.047523,0.047687,-0.028220,0.544209,1.000000,0.128297,0.231406,0.083890
Rewards point redeemed in 12months,0.046782,-0.055740,-0.031298,0.152249,0.084903,0.286496,0.346071,0.243807,0.250397,0.270417,...,0.056989,0.023361,0.057876,0.119083,0.084869,0.013540,0.128297,1.000000,0.092900,0.094893
Emails Open in Last 6 months,0.071878,-0.034583,0.090208,0.042737,0.074443,0.027649,0.055904,0.034980,0.018867,0.018319,...,0.027540,0.017928,-0.037748,0.143557,0.081407,0.367762,0.231406,0.092900,1.000000,0.283364
Emails Clicked in Last 6 months,0.008297,-0.031842,0.013358,0.088536,0.030592,0.062963,0.095959,0.057971,0.061353,0.056497,...,-0.012770,-0.037809,0.005344,0.062919,0.029749,0.096413,0.083890,0.094893,0.283364,1.000000